auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: ericcoderr.github.io
url: http://ericcoderr.github.io
feed: /atom.xml
author_info: <a href="http://ericcoderr.github.io/">BeiYuu</a>
